--
-- PostgreSQL database dump
--

\restrict ZNzKN6Z3THHjkgiylp5yeIh8SopdTVEKYk0oSEDqsF88A1JP545LZ94cPVErnbw

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

-- Started on 2026-06-23 00:37:03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 24601)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 24600)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 24586)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24614)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 24613)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 24626)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24638)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 24655)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 24593)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "Name" text NOT NULL,
    "Surname" text NOT NULL,
    "ProfilePictureUrl" text,
    "CompanyName" text,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 24668)
-- Name: EvaluationHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EvaluationHistory" (
    "Id" integer NOT NULL,
    "ModelName" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "AiScore" text DEFAULT ''::text NOT NULL,
    "UserId" text NOT NULL,
    "CarbonFootprint" double precision DEFAULT 0.0 NOT NULL,
    "CostUsd" double precision DEFAULT 0.0 NOT NULL,
    "EnergyKwh" double precision DEFAULT 0.0 NOT NULL,
    "HoursSaved" double precision DEFAULT 0.0 NOT NULL,
    "IsApproved" boolean DEFAULT false NOT NULL,
    "RiskScore" double precision DEFAULT 0.0 NOT NULL,
    "WaterFootprintLiters" double precision DEFAULT 0.0 NOT NULL
);


ALTER TABLE public."EvaluationHistory" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24667)
-- Name: EvaluationHistory_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EvaluationHistory" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EvaluationHistory_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 24581)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4966 (class 0 OID 24601)
-- Dependencies: 221
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4963 (class 0 OID 24586)
-- Dependencies: 218
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4968 (class 0 OID 24614)
-- Dependencies: 223
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4969 (class 0 OID 24626)
-- Dependencies: 224
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4970 (class 0 OID 24638)
-- Dependencies: 225
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4971 (class 0 OID 24655)
-- Dependencies: 226
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 4964 (class 0 OID 24593)
-- Dependencies: 219
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."AspNetUsers" VALUES ('497be1a7-7190-435c-8a79-d4cb77e4754e', 'Hugo', 'DE SOUSA DIAS', NULL, 'Efrei Finance', 'leon.test@efrei.fr', 'LEON.TEST@EFREI.FR', 'leon.test@efrei.fr', 'LEON.TEST@EFREI.FR', false, 'AQAAAAIAAYagAAAAEE+I/vu7K9DNsOanTDGIhGHm4k/rFPDW62DGp+5NKZI7FyHBCH7tZuS7JeiGSzU8Ng==', 'U4UE5QZSX63B23OB3WQLXSG4G3H33QA6', 'f6fbb403-6c6b-4b73-9932-321ba37b8a18', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" VALUES ('99007fcc-42d6-4139-8a02-58da660d7015', 'Hugo', 'DE SOUSA DIAS', NULL, 'Efrei Finance', 'romeo.test@efrei.fr', 'ROMEO.TEST@EFREI.FR', 'romeo.test@efrei.fr', 'ROMEO.TEST@EFREI.FR', false, 'AQAAAAIAAYagAAAAEN1fe8IUqCxAvr9tAjmGK6bz5aY44O5N9j/kD6ib+gPFolVriYWKR865MSt00CBv1Q==', 'P7ZVTJKW4EQBYQ6ZRBMDIUIWFSDJQ7XJ', '7cc520aa-51e1-42ad-adab-16dfcc4f8233', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" VALUES ('3fffd812-b799-4dbe-806d-95fa7a0479ba', 'Hugo', 'DE SOUSA DIAS', NULL, 'Efrei Finance', 'hassane.test@efrei.fr', 'HASSANE.TEST@EFREI.FR', 'hassane.test@efrei.fr', 'HASSANE.TEST@EFREI.FR', false, 'AQAAAAIAAYagAAAAEBLpx3r4sP0oqcrHsMZS7yLUXviu2R/K1pV5OxigqUdprG7rBNgsmZQxp4pAnGomSw==', 'CUMLGXFLG37UNYB4QCFJHWCJGG4CWLUC', '092f3981-f76b-40e5-a610-5b53d1d9108e', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" VALUES ('e93222c3-1e6e-4d8a-b253-7835018fd02e', 'Hugo', 'DE SOUSA DIAS', NULL, 'Efrei Finance', 'bruno.test@efrei.fr', 'BRUNO.TEST@EFREI.FR', 'bruno.test@efrei.fr', 'BRUNO.TEST@EFREI.FR', false, 'AQAAAAIAAYagAAAAEGeKsEHXAc1HpwEPA99I0gD9xH1Zs3yMEONt8sejJ5ryfwfwMsfhcBXm0AviIilNig==', 'SYJWZA2VIDTX6NFYCNZCCHT2P7HDX3DF', 'dafb52f9-8a19-4504-bd5b-87ebee0b0b62', NULL, false, false, NULL, true, 0);


--
-- TOC entry 4973 (class 0 OID 24668)
-- Dependencies: 228
-- Data for Name: EvaluationHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."EvaluationHistory" VALUES (1, 'DeepSeek V3.1', '2026-06-22 21:47:13.781863+02', '', '497be1a7-7190-435c-8a79-d4cb77e4754e', 0.0005941194822, 0.004900000000000001, 0.007417222, 6.5, true, 2.5, 0.00623046648);
INSERT INTO public."EvaluationHistory" VALUES (2, 'DeepSeek V3.1', '2026-06-22 21:48:37.936939+02', '', '497be1a7-7190-435c-8a79-d4cb77e4754e', 0.0005941194822, 0.004900000000000001, 0.007417222, 6.5, false, 4, 0.00623046648);
INSERT INTO public."EvaluationHistory" VALUES (3, 'DeepSeek V3.1', '2026-06-22 21:48:42.968222+02', '', '497be1a7-7190-435c-8a79-d4cb77e4754e', 0, 0, 0, 0, false, 0, 0);
INSERT INTO public."EvaluationHistory" VALUES (5, 'DeepSeek V3.1', '2026-06-22 22:52:54.484802+02', 'Utile', '3fffd812-b799-4dbe-806d-95fa7a0479ba', 0.0005941194822, 0.004900000000000001, 0.007417222, 6.5, false, 4.5, 0.00623046648);
INSERT INTO public."EvaluationHistory" VALUES (4, 'DeepSeek V3.1', '2026-06-22 22:52:48.957423+02', 'cool', '3fffd812-b799-4dbe-806d-95fa7a0479ba', 0, 0, 0, 0, false, 0, 0);


--
-- TOC entry 4962 (class 0 OID 24581)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20260603204404_InitialSetup', '10.0.8');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260611105536_InitialCreateWithRelations', '10.0.8');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20260622164627_AddFullEvaluationMetrics', '10.0.8');


--
-- TOC entry 4979 (class 0 OID 0)
-- Dependencies: 220
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 4980 (class 0 OID 0)
-- Dependencies: 222
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 4981 (class 0 OID 0)
-- Dependencies: 227
-- Name: EvaluationHistory_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EvaluationHistory_Id_seq"', 5, true);


--
-- TOC entry 4795 (class 2606 OID 24607)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4787 (class 2606 OID 24592)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 4798 (class 2606 OID 24620)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 4801 (class 2606 OID 24632)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 4804 (class 2606 OID 24644)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 4806 (class 2606 OID 24661)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 4791 (class 2606 OID 24599)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 4809 (class 2606 OID 24674)
-- Name: EvaluationHistory PK_EvaluationHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EvaluationHistory"
    ADD CONSTRAINT "PK_EvaluationHistory" PRIMARY KEY ("Id");


--
-- TOC entry 4785 (class 2606 OID 24585)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4789 (class 1259 OID 24685)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 4793 (class 1259 OID 24680)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 4796 (class 1259 OID 24682)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 4799 (class 1259 OID 24683)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 4802 (class 1259 OID 24684)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 4807 (class 1259 OID 24687)
-- Name: IX_EvaluationHistory_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EvaluationHistory_UserId" ON public."EvaluationHistory" USING btree ("UserId");


--
-- TOC entry 4788 (class 1259 OID 24681)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 4792 (class 1259 OID 24686)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 4810 (class 2606 OID 24608)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 4811 (class 2606 OID 24621)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4812 (class 2606 OID 24633)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4813 (class 2606 OID 24645)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 4814 (class 2606 OID 24650)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4815 (class 2606 OID 24662)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 4816 (class 2606 OID 24675)
-- Name: EvaluationHistory FK_EvaluationHistory_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EvaluationHistory"
    ADD CONSTRAINT "FK_EvaluationHistory_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


-- Completed on 2026-06-23 00:37:03

--
-- PostgreSQL database dump complete
--

\unrestrict ZNzKN6Z3THHjkgiylp5yeIh8SopdTVEKYk0oSEDqsF88A1JP545LZ94cPVErnbw

